---
- name: use hosts.j2 template
  hosts: all
  tasks:
   - name: template a file to dev hosts
     template: 
      src: /home/sandy/ansible/hosts.j2
      dest: /root/myhosts
     when: "'dev' in group_names"
...
