---
- name: change issue file
  hosts: all
  tasks:
      - name: change dev hosts issue file
        copy:
           content: "Development"
           dest: /etc/issue
        when: '"dev" in group_names'
      - name: change test hosts issue file
        copy:
           content: "Test"
           dest: /etc/issue
        when: '"test" in group_names'
      - name: change prod hosts issue file
        copy:
           content: "Producation"
           dest: /etc/issue
        when: '"prod" in group_names'
...
